name: Deploy Javascript Program

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install

      - name: Build the project
        run: npm run build



  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

          
          
      - name: Deploy Debian12
        run: |
          ssh -o StrictHostKeyChecking=no ict@102.221.238.122 << 'EOF'
            mkdir -p /home/ict/ci-cd
            # Navigate to the application directory
            cd /home/ict/ci-cd || exit 1
            git init
            git pull origin main
            npm install  # For Node.js applications
            # pip install -r requirements.txt  # For Python applications

            # Restart the application or service (modify according to your setup)
            # systemctl restart your-service  # If using systemd
            # pm2 restart your-app  # If using PM2 for Node.js

            # Optional: Clear cache, build assets, etc. depending on your setup
            npm run start
          EOF
