name: Deploy Javascript Program

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Debian12
        run: |
          ssh -o StrictHostKeyChecking=no ict@102.221.238.122 << 'EOF'
            
            mkdir -p /home/ict/ci-cd

            # Navigate to the application directory
            cd /home/ict/ci-cd || exit 1

            # Clone the repository (this will replace existing files in the directory)
            git clone https://github.com/malimikillua/node-test.git . || git pull origin main
             npm install  # For Node.js applications
            # pip install -r requirements.txt  # For Python applications

            # Restart the application or service (modify according to your setup)
            # systemctl restart your-service  # If using systemd
            # pm2 restart your-app  # If using PM2 for Node.js

            # Optional: Clear cache, build assets, etc. depending on your setup
             npm run dev
          EOF
